Add 4 Searchning algorithms
codesankalp/dsalgo pull request #30
Opened 2020-09-25 07:03 UTC by Vivekagent47

Added Searching Algos:
1- Linear Search
2- Binary Search
3- Jump Search
4- Fibonacci Search

2020-09-25 07:04 UTC, Vivekagent47 commented
Please review it.

2020-09-25 07:18 UTC, codesankalp requested changes
Also add tests for your code.

2020-09-25 07:18 UTC, codesankalp commented on dsalgo/search.py
> +    first = 0
add a conditional check to check whether the passed array is sorted or not to avoid unexpected results.

2020-09-25 07:18 UTC, codesankalp commented on dsalgo/search.py
> +
same thing as mentioned above and wherever a sorted array is required.

2020-09-25 07:18 UTC, codesankalp commented on dsalgo/search.py
> +    return -1
add a new line when your code finishes. Read contributing guidelines (pep8 style guidelines)

2020-09-25 07:18 UTC, codesankalp commented on dsalgo/search.py
> +        args:
Describe parameters using sphinx way.
```
Parameters
----------
param : type
             Description of parameter `param`.
```
Also write tests for your code.

2020-09-28 07:57 UTC, codesankalp commented
@Vivekagent47 we will not approve your pull request until it's linked with an issue.
Linking the issue with pull request is a must step.
Also make the code changes.

2020-09-28 07:58 UTC, closed without merging