BST_Traversal_Algo
codesankalp/dsalgo pull request #34
Opened 2020-09-27 08:53 UTC by shaonakundu

I have created Binary Search Tree traversal algorithms(Pre, post and inorder) in dsalgo folder using Python. Thanks for assigning me this task for Hactoberfest2020 and it was wonderful to contribute.

2020-09-27 15:27 UTC, Aryamanz29 requested changes
```
l = int(input())

arr = list(map(int, input().split()))

for i in range(l):
	tree.create(arr[i])


preorder(tree.root)
postorder(tree.root)
inorder(tree.root
```

For testing use python test framework unittest and add your test cases their only implementation of BST algo will remain in **BST_Traversal_Algorithms.py** .The path where you going to write tests for this issue is **dsalgo/tests** & named as "BST_algo_test.py". For more info regarding unittest framework visit:
[](https://docs.python.org/2/library/unittest.html)

2020-09-27 17:25 UTC, shaonakundu commented
> ```
> l = int(input())
> 
> arr = list(map(int, input().split()))
> 
> for i in range(l):
> 	tree.create(arr[i])
> 
> 
> preorder(tree.root)
> postorder(tree.root)
> inorder(tree.root
> ```
> 
> For testing use python test framework unittest and add your test cases their only implementation of BST algo will remain in **BST_Traversal_Algorithms.py** .The path where you going to write tests for this issue is **dsalgo/tests** & named as "BST_algo_test.py". For more info regarding unittest framework visit:

Hey, I have uploaded the unittest, can you check and let me know if its correct or not

2020-09-27 22:18 UTC, devkapilbansal requested changes
@shaonakundu link the issue in your commit. Also, squash your commits in one. It's always better to have a single commit for an issue to track it later

2020-09-28 04:21 UTC, shaonakundu commented
> @shaonakundu link the issue in your commit. Also, squash your commits in one. It's always better to have a single commit for an issue to track it later

Its not an issue I was asked to add another file to tests folder, so I asked to check it

2020-09-28 07:55 UTC, codesankalp commented
@shaonakundu we will not approve your pull request until it's linked with an issue.
Linking the issue with pull request is a must step.
Also make the code changes as mengtioned by @devkapilbansal

2020-09-28 08:03 UTC, shaonakundu commented
Ok so you mean this tree traversal issue to be linked with pull request?

2020-09-28 08:08 UTC, shaonakundu commented
Can you guide me how to link the issue with pull req

2020-09-28 08:28 UTC, Aryamanz29 requested changes

2020-09-28 08:28 UTC, Aryamanz29 commented on dsalgo/BST_Traversal_Algorithms.py
> +
Please use proper docstring syntax """

2020-09-28 08:28 UTC, Aryamanz29 commented on dsalgo/BST_Traversal_Algorithms.py
> +		 if self.root = None:
`if self.root==None:`

2020-09-28 08:48 UTC, Aryamanz29 commented
> Hey, I have uploaded the unittest, can you check and let me know if it's correct or not
Hello, after reviewing your code and locally  I have found many errors in both files (like improper indentations, no module name error in the test file, and many more). Kindly before creating any PR check your code locally and one more thing when you are using unittest framework use their inbuilt methods to check whether the test passes or not ( some methods are **assertEqual()**, **assetnotEqual()**, and many more)

2020-10-01 16:28 UTC, Aryamanz29 commented
> > Hey, I have uploaded the unittest, can you check and let me know if it's correct or not
> 
> Hello, after reviewing your code locally I have found many errors in both files (like improper indentations, no module name error in the test file, and many more).
> Kindly before creating any PR check your code locally and one more thing when you are using unittest framework use their inbuilt methods to check whether the test passes or not ( some methods are **assertEqual()**, **assetnotEqual()**, and many more)

@shaonakundu  Are you working on this issue?

2020-10-01 16:30 UTC, shaonakundu commented
> > > Hey, I have uploaded the unittest, can you check and let me know if it's correct or not
> > 
> > 
> > Hello, after reviewing your code locally I have found many errors in both files (like improper indentations, no module name error in the test file, and many more).
> > Kindly before creating any PR check your code locally and one more thing when you are using unittest framework use their inbuilt methods to check whether the test passes or not ( some methods are **assertEqual()**, **assetnotEqual()**, and many more)
> 
> @shaonakundu Are you working on this issue?

I tried a lot but there is some issue with my system , you can unassign me, sorry for the inconvinience

2020-10-01 16:40 UTC, devkapilbansal commented
@shaonakundu I would suggest you wait for some time. As this is almost complete we will look into this and will try to help

2020-10-01 16:44 UTC, shaonakundu commented
> @shaonakundu I would suggest you wait for some time. As this is almost complete we will look into this and will try to help

Ok i dont know why its saying no module although its there and i tried with relative path also still and indentation error because I wrote it in correct format but still the issue is still there

2020-10-01 18:11 UTC, closed without merging