Added tests for linked_list.py #39
codesankalp/dsalgo pull request #48
Opened 2020-09-30 20:37 UTC by Aryamanz29

-Added test file for linked_list.py
-remove linked_list_tests.ipynb from dsalgo/tests
closes #39

2020-10-01 07:14 UTC, codesankalp approved these changes

2020-10-01 18:38 UTC, codesankalp requested changes

2020-10-01 18:38 UTC, codesankalp commented on tests/linkedlist_tests.py
> +          self.assertEqual(self.list,self.ls.to_list())
use flake8 for styling purpose.

2020-10-01 18:39 UTC, Aryamanz29 commented on tests/linkedlist_tests.py
> +          self.assertEqual(self.list,self.ls.to_list())
already checked pep8 styling no issue

2020-10-02 05:46 UTC, devkapilbansal commented on tests/linkedlist_tests.py
> +
Why so many blank lines here?

2020-10-04 08:25 UTC, Aryamanz29 commented on tests/linkedlist_tests.py
> +
Done 😊

2020-10-04 08:38 UTC, ravi5175 approved these changes

2020-10-06 19:40 UTC, 17sushmita requested changes

2020-10-06 19:40 UTC, 17sushmita commented on tests/linkedlist_tests.py
> +import unittest
rename this file to test_linkedlist.py

2020-10-06 19:40 UTC, 17sushmita commented on tests/linkedlist_tests.py
> +    unittest.main()
remove the driver code

2020-10-06 19:40 UTC, 17sushmita commented on tests/linkedlist_tests.py
> +
for good testing practice, you can use random module and generate a list of random numbers to test

2020-10-07 12:53 UTC, Aryamanz29 commented
One thing I noticed when writing the test for the Linked list is that reverse() is not working properly, It only reverses the list when sorted & not working for random values. So please check linked_list.py if you got the same problem, we can create a new issue for that including the test.

2020-10-07 13:30 UTC, 17sushmita commented
> One thing I noticed when writing the test for the Linked list is that reverse() is not working properly, It only reverses the list when sorted & not working for random values. So please check linked_list.py if you got the same problem, we can create a new issue for that including the test.

Can you provide some screenshots because It is working for the test case I tested on.

2020-10-07 13:39 UTC, Aryamanz29 commented
> > One thing I noticed when writing the test for the Linked list is that reverse() is not working properly, It only reverses the list when sorted & not working for random values. So please check linked_list.py if you got the same problem, we can create a new issue for that including the test.
> 
> Can you provide some screenshots because It is working for the test case I tested on.

![Screenshot (70)](https://user-images.githubusercontent.com/56113566/95338502-9de23700-08d0-11eb-97ba-4fb0dbc471fc.png)
![Screenshot (69)](https://user-images.githubusercontent.com/56113566/95338507-a0dd2780-08d0-11eb-9d9c-4203bc551ac4.png)

2020-10-07 14:22 UTC, codesankalp commented
@Aryamanz29 there is no problem in the code actually you tried the wrong way.
see this:
```
self.rev1 = self.list.copy()[ : :-1]
self.ls.reverse()
self.assertEqual(self.rev1, self.ls.to_list())
```
I think with the above code you will understand what is wrong.

2020-10-07 15:53 UTC, Aryamanz29 commented
> @Aryamanz29 there is no problem in the code actually you tried the wrong way.
> see this:
> 
> ```
> self.rev1 = self.list.copy()[ : :-1]
> self.ls.reverse()
> self.assertEqual(self.rev1, self.ls.to_list())
> ```
> 
> I think with the above code you will understand what is wrong.

ohk i got this thanks👍

2022-05-06 02:56 UTC, closed without merging