Binary Tree
codesankalp/dsalgo pull request #69
Opened 2020-10-03 11:33 UTC by Hinal-Srivastava

[#19](https://github.com/codesankalp/dsalgo/issues/19). A Transversing Binary Tree in Python is implemented.

2020-10-03 11:37 UTC, ravi5175 commented
@Hinal-Srivastava please provide more details like unittest or explaining more about your code

2020-10-03 11:50 UTC, codesankalp commented
@Hinal-Srivastava please do these changes:
- follow our commit template.
- read our contributing guidelines
- read about how to link a issue with the pr (pr guidelines)
- add tests for your work
- attach screenshot here.

Thanks for contributing.

2020-10-06 15:01 UTC, codesankalp commented
@Hinal-Srivastava are you still working on this?

2020-10-06 15:15 UTC, Hinal-Srivastava commented
> @Hinal-Srivastava are you still working on this?

Yes. I'll update it by tonight

2020-10-07 15:47 UTC, Hinal-Srivastava commented
> @Hinal-Srivastava please do these changes:
> 
> * follow our commit template.
> * read our contributing guidelines
> * read about how to link a issue with the pr (pr guidelines)
> * add tests for your work
> * attach screenshot here.
> 
> Thanks for contributing.

I didn't find any commit template

2020-10-07 15:54 UTC, Hinal-Srivastava commented
![image](https://user-images.githubusercontent.com/28009493/95355675-7052b900-08e3-11eb-96d9-6a7241aa88f6.png)

2020-10-07 16:07 UTC, 17sushmita requested changes
Read the documentation README.rst. We're developing a python library so you need not to test your code in the module. Make a separate test file in tests folder and implement unittesting.

2020-10-07 16:07 UTC, 17sushmita commented on dsalgo/binary_tree.py
> +print(tree.search(s))
Don't use driver code here. Make a file for unittesting and test the operations you've implemented in the tree. You can check `tests` directory in the repo for more context.

2020-10-13 16:39 UTC, codesankalp commented
@Hinal-Srivastava are you still working on this?

2020-10-13 16:40 UTC, codesankalp commented on dsalgo/binary_tree.py
> +print(tree.search(s))
add a new line at the end of line and follow pep8 guidelines or read our contributing.md

2020-10-21 12:03 UTC, devkapilbansal commented
@Hinal-Srivastava please made the necessary changes as requested

2021-10-02 07:17 UTC, Aryamanz29 commented
Closing this PR, Since contributor is inactive
Thanks

2021-10-02 07:17 UTC, closed without merging