Search
codesankalp/dsalgo pull request #73
Opened 2020-10-05 13:17 UTC by nisheksharma

### Description

### Related Issue

** Please don't create a Pull request without creating an issue first **

Fixes # [ISSUE]

### Type of Change:

- Code
- Quality Assurance
- Documentation

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)

### Motivation and Context

### How Has This Been Tested?

### Checklist:

- [ ] I read the **CONTRIBUTING** document before making this pull request
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] My change requires change to documentation
- [ ] I have updated documentation accordingly
- [ ] I have updated the requirements file
- [ ] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

### Screenshots (if appropriate):

2020-10-05 13:26 UTC, codesankalp requested changes
You have to link your issue with pull request.
Try to do the mentioned changes.

2020-10-05 13:26 UTC, codesankalp commented on README.md
> +# dsalgo
no need to update the readme.
check our new readme.

2020-10-05 13:26 UTC, codesankalp commented on dsalgo/search.py
> +    # Iterative Binary Search Function
add docstrings.

2020-10-05 13:26 UTC, codesankalp commented on dsalgo/search.py
> +    # Example:
no need to write comments to explain because no one is going to read this.

2020-10-05 13:26 UTC, codesankalp commented on dsalgo/search.py
> +        return -1
add lines between them
use flake 8

2020-10-05 13:26 UTC, codesankalp commented on dsalgo/search.py
> +    # If x is present in arr[0..n-1], then returns
again wrong format.

2020-10-05 13:26 UTC, codesankalp commented on dsalgo/search.py
> +        # Find indexs of two corners
add docstring

2020-10-05 13:26 UTC, codesankalp commented on dsalgo/search.py
> +if __name__ == "__main__":
no need for this,

2020-10-05 13:26 UTC, codesankalp commented on dsalgo/search.py
> +        low = 0
where is __init__

2020-10-05 13:28 UTC, codesankalp commented
also this branch have conflicts so rebase your branch with master,
try to squash commit into one

2020-10-06 15:00 UTC, codesankalp commented
@nisheksharma  after 2 days if you don't change anything then it will be marked as invalid.

2020-10-07 10:15 UTC, nisheksharma commented
@codesankalp review

2020-10-07 10:16 UTC, codesankalp approved these changes
Tested all the code and works properly.
Code styling is also good.
It is ready to merge.

2020-10-07 10:17 UTC, codesankalp commented
@Aryamanz29 
@17sushmita 
please review this pr.

2020-10-07 10:19 UTC, devkapilbansal requested changes
@nisheksharma rename your file to test_search

2020-10-07 10:20 UTC, devkapilbansal commented
Also, please follow commit message guidelines

2020-10-07 10:22 UTC, devkapilbansal commented
Pinging @17sushmita for testing code locally before merge

2020-10-07 10:28 UTC, devkapilbansal commented
Thanks @nisheksharma just one last request from my side. Change type to feature instead of file, as file is not a commit type defined in our guidelines

2020-10-07 10:35 UTC, codesankalp approved these changes

2020-10-07 10:59 UTC, nisheksharma commented
> @nisheksharma rename your file to test_search

Done

2020-10-07 11:00 UTC, nisheksharma commented
> Thanks @nisheksharma just one last request from my side. Change type to feature instead of file, as file is not a commit type defined in our guidelines

done

2020-10-07 13:39 UTC, devkapilbansal approved these changes
@nishesksharma thanks Made some changes. Hope you don't mind

2020-10-07 13:40 UTC, devkapilbansal commented
LGTM 👍 Thanks @nisheksharma

2020-10-07 13:40 UTC, merged