updated available algorithms list
codesankalp/dsalgo pull request #84
Opened 2021-10-08 05:28 UTC by ravi5175

### Description
Added a list of available algorithms in module to the readme

Fixes #83

### Checklist:
- [* ] I read the **CONTRIBUTING** document before making this pull request
- [* ] My code follows the style guidelines of this project
- [*] I have performed a self-review of my own code or materials
- [* ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [*] My change requires change to documentation
- [* ] I have updated documentation accordingly
- [* ] My changes generate no new warnings 
- [* ] All new and existing tests passed

2021-10-08 05:59 UTC, codesankalp requested changes
With links to the file will be better.

2021-10-14 05:28 UTC, ravi5175 commented
@codesankalp commited requested changes

2021-10-14 06:48 UTC, codesankalp commented on README.rst
> +** ALGORITHMS AVAILABLE**
```suggestion
**ALGORITHMS AVAILABLE**
```

2021-10-14 06:49 UTC, codesankalp commented on README.rst
> +* Linked List algorithms `link <https://github.com/codesankalp/dsalgo/blob/master/dsalgo/linked_list.py>`_
```suggestion
* `Linked List algorithms <https://github.com/codesankalp/dsalgo/blob/master/dsalgo/linked_list.py>`_
```
And for other also.

2021-10-14 06:50 UTC, codesankalp requested changes
@ravi5175  I have reviewed it, It will be better if the headline will be link.

2021-10-14 06:51 UTC, ravi5175 commented on README.rst
> +* Linked List algorithms `link <https://github.com/codesankalp/dsalgo/blob/master/dsalgo/linked_list.py>`_
> @ravi5175 I have reviewed it, It will be better if the headline will be link.

sure i will fix

2021-10-14 07:06 UTC, codesankalp approved these changes

2021-10-15 05:57 UTC, Aryamanz29 approved these changes

2021-10-15 05:58 UTC, merged